package:
  name: stable-diffusion-sdkit
  version: "2.1.5"

source:
  - url: https://files.pythonhosted.org/packages/66/bb/c629ade35f13a34cd00a5cf4825d906128e9ef0412f415ecd1ee6956465d/stable-diffusion-sdkit-2.1.5.tar.gz
    sha256: 49ae507129bf54a181fe79f48dbaf3d4ca475e58af48f2ce374af5e7cc0c652c

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - albumentations
    - py-opencv
    - lightning
    - omegaconf
    - einops
    - transformers
    - open-clip-torch
    - tqdm

tests:
  - python:
      imports:
        - ldm
      pip_check: true

about:
  license: MIT
  summary: High-Resolution Image Synthesis with Latent Diffusion Models. This is a wrapper around the original repo, to allow installing via pip.

extra:
  recipe-maintainers:
    - itskyf
